[package]
name = "aoc-2021"
version = "0.1.0"
authors = ["Anton Österberg <anton@42x.io>"]
edition = "2021"

[dependencies]
regex = "1.3"
log = "0.4"
env_logger = "0.7"
termcolor = "1.1"
lazy_static = "1.4"
itertools = "0.9"
aoc = { git = "https://github.com/mantono/aoc.git", rev = "8771c53" }